columns:
  - unit_number: int
  - time_in_cycles: int
  - set_1: int
  - set_2: int
  - set_3: int
  - sen_1: int
  - sen_2: int
  - sen_3: int
  - sen_4: int
  - sen_5: int
  - sen_6: int
  - sen_7: int
  - sen_8: int
  - sen_9: int
  - sen_10: int
  - sen_11: int
  - sen_12: int
  - sen_13: int
  - sen_14: int
  - sen_15: int
  - sen_16: int
  - sen_17: int
  - sen_18: int
  - sen_19: int
  - sen_20: int
  - sen_21: int